/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V2IndexRouteImport } from './routes/v2.index'
import { Route as V2SettingsRouteImport } from './routes/v2.settings'
import { Route as V2ProductionUnitsRouteImport } from './routes/v2.production-units'
import { Route as V2InventoryRouteImport } from './routes/v2.inventory'
import { Route as V2FinanceRouteImport } from './routes/v2.finance'
import { Route as V2DashboardRouteImport } from './routes/v2.dashboard'
import { Route as V2AlertsRouteImport } from './routes/v2.alerts'
import { Route as PublicLayoutRouteImport } from './routes/_public/_layout'
import { Route as PublicLayoutSignupRouteImport } from './routes/_public/_layout/signup'
import { Route as PublicLayoutLoginRouteImport } from './routes/_public/_layout/login'
import { Route as CompatFarmIdSpeciesIdAnimalIdRouteImport } from './routes/compat.$farmId.$speciesId.$animalId'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2IndexRoute = V2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2Route,
} as any)
const V2SettingsRoute = V2SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => V2Route,
} as any)
const V2ProductionUnitsRoute = V2ProductionUnitsRouteImport.update({
  id: '/production-units',
  path: '/production-units',
  getParentRoute: () => V2Route,
} as any)
const V2InventoryRoute = V2InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => V2Route,
} as any)
const V2FinanceRoute = V2FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => V2Route,
} as any)
const V2DashboardRoute = V2DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => V2Route,
} as any)
const V2AlertsRoute = V2AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => V2Route,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutSignupRoute = PublicLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutLoginRoute = PublicLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const CompatFarmIdSpeciesIdAnimalIdRoute =
  CompatFarmIdSpeciesIdAnimalIdRouteImport.update({
    id: '/compat/$farmId/$speciesId/$animalId',
    path: '/compat/$farmId/$speciesId/$animalId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v2': typeof V2RouteWithChildren
  '/v2/alerts': typeof V2AlertsRoute
  '/v2/dashboard': typeof V2DashboardRoute
  '/v2/finance': typeof V2FinanceRoute
  '/v2/inventory': typeof V2InventoryRoute
  '/v2/production-units': typeof V2ProductionUnitsRoute
  '/v2/settings': typeof V2SettingsRoute
  '/v2/': typeof V2IndexRoute
  '/login': typeof PublicLayoutLoginRoute
  '/signup': typeof PublicLayoutSignupRoute
  '/compat/$farmId/$speciesId/$animalId': typeof CompatFarmIdSpeciesIdAnimalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/v2/alerts': typeof V2AlertsRoute
  '/v2/dashboard': typeof V2DashboardRoute
  '/v2/finance': typeof V2FinanceRoute
  '/v2/inventory': typeof V2InventoryRoute
  '/v2/production-units': typeof V2ProductionUnitsRoute
  '/v2/settings': typeof V2SettingsRoute
  '/v2': typeof V2IndexRoute
  '/login': typeof PublicLayoutLoginRoute
  '/signup': typeof PublicLayoutSignupRoute
  '/compat/$farmId/$speciesId/$animalId': typeof CompatFarmIdSpeciesIdAnimalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/v2': typeof V2RouteWithChildren
  '/_public/_layout': typeof PublicLayoutRouteWithChildren
  '/v2/alerts': typeof V2AlertsRoute
  '/v2/dashboard': typeof V2DashboardRoute
  '/v2/finance': typeof V2FinanceRoute
  '/v2/inventory': typeof V2InventoryRoute
  '/v2/production-units': typeof V2ProductionUnitsRoute
  '/v2/settings': typeof V2SettingsRoute
  '/v2/': typeof V2IndexRoute
  '/_public/_layout/login': typeof PublicLayoutLoginRoute
  '/_public/_layout/signup': typeof PublicLayoutSignupRoute
  '/compat/$farmId/$speciesId/$animalId': typeof CompatFarmIdSpeciesIdAnimalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/v2'
    | '/v2/alerts'
    | '/v2/dashboard'
    | '/v2/finance'
    | '/v2/inventory'
    | '/v2/production-units'
    | '/v2/settings'
    | '/v2/'
    | '/login'
    | '/signup'
    | '/compat/$farmId/$speciesId/$animalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/v2/alerts'
    | '/v2/dashboard'
    | '/v2/finance'
    | '/v2/inventory'
    | '/v2/production-units'
    | '/v2/settings'
    | '/v2'
    | '/login'
    | '/signup'
    | '/compat/$farmId/$speciesId/$animalId'
  id:
    | '__root__'
    | '/'
    | '/v2'
    | '/_public/_layout'
    | '/v2/alerts'
    | '/v2/dashboard'
    | '/v2/finance'
    | '/v2/inventory'
    | '/v2/production-units'
    | '/v2/settings'
    | '/v2/'
    | '/_public/_layout/login'
    | '/_public/_layout/signup'
    | '/compat/$farmId/$speciesId/$animalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  V2Route: typeof V2RouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  CompatFarmIdSpeciesIdAnimalIdRoute: typeof CompatFarmIdSpeciesIdAnimalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/': {
      id: '/v2/'
      path: '/'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2IndexRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/settings': {
      id: '/v2/settings'
      path: '/settings'
      fullPath: '/v2/settings'
      preLoaderRoute: typeof V2SettingsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/production-units': {
      id: '/v2/production-units'
      path: '/production-units'
      fullPath: '/v2/production-units'
      preLoaderRoute: typeof V2ProductionUnitsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/inventory': {
      id: '/v2/inventory'
      path: '/inventory'
      fullPath: '/v2/inventory'
      preLoaderRoute: typeof V2InventoryRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/finance': {
      id: '/v2/finance'
      path: '/finance'
      fullPath: '/v2/finance'
      preLoaderRoute: typeof V2FinanceRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/dashboard': {
      id: '/v2/dashboard'
      path: '/dashboard'
      fullPath: '/v2/dashboard'
      preLoaderRoute: typeof V2DashboardRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/alerts': {
      id: '/v2/alerts'
      path: '/alerts'
      fullPath: '/v2/alerts'
      preLoaderRoute: typeof V2AlertsRouteImport
      parentRoute: typeof V2Route
    }
    '/_public/_layout': {
      id: '/_public/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_layout/signup': {
      id: '/_public/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicLayoutSignupRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/_layout/login': {
      id: '/_public/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLayoutLoginRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/compat/$farmId/$speciesId/$animalId': {
      id: '/compat/$farmId/$speciesId/$animalId'
      path: '/compat/$farmId/$speciesId/$animalId'
      fullPath: '/compat/$farmId/$speciesId/$animalId'
      preLoaderRoute: typeof CompatFarmIdSpeciesIdAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface V2RouteChildren {
  V2AlertsRoute: typeof V2AlertsRoute
  V2DashboardRoute: typeof V2DashboardRoute
  V2FinanceRoute: typeof V2FinanceRoute
  V2InventoryRoute: typeof V2InventoryRoute
  V2ProductionUnitsRoute: typeof V2ProductionUnitsRoute
  V2SettingsRoute: typeof V2SettingsRoute
  V2IndexRoute: typeof V2IndexRoute
}

const V2RouteChildren: V2RouteChildren = {
  V2AlertsRoute: V2AlertsRoute,
  V2DashboardRoute: V2DashboardRoute,
  V2FinanceRoute: V2FinanceRoute,
  V2InventoryRoute: V2InventoryRoute,
  V2ProductionUnitsRoute: V2ProductionUnitsRoute,
  V2SettingsRoute: V2SettingsRoute,
  V2IndexRoute: V2IndexRoute,
}

const V2RouteWithChildren = V2Route._addFileChildren(V2RouteChildren)

interface PublicLayoutRouteChildren {
  PublicLayoutLoginRoute: typeof PublicLayoutLoginRoute
  PublicLayoutSignupRoute: typeof PublicLayoutSignupRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutLoginRoute: PublicLayoutLoginRoute,
  PublicLayoutSignupRoute: PublicLayoutSignupRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  V2Route: V2RouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  CompatFarmIdSpeciesIdAnimalIdRoute: CompatFarmIdSpeciesIdAnimalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
