import type {
	EventCategory,
	FarmEvent,
	FarmWorkspace,
	Individual,
	InventoryItem,
	ProductionUnit,
} from "@/shared/types/v2-domain-types";

const today = new Date();

function toIsoFromToday(daysOffset: number, hours: number): string {
	const value = new Date(today);
	value.setDate(value.getDate() + daysOffset);
	value.setHours(hours, 0, 0, 0);
	return value.toISOString();
}

export const v2FarmSeed: FarmWorkspace = {
	id: "farm-001",
	name: "Farmhouse",
	timezone: "America/Guayaquil",
	currency: "USD",
};

export const v2UnitSeed: ProductionUnit[] = [
	{
		id: "unit-layer-a",
		farmId: "farm-001",
		name: "Lote ponedoras A",
		categoryLabel: "Chicken",
		mode: "aggregate",
		status: "active",
		location: "Coop 1",
		tags: ["eggs", "daily"],
		headCount: 47,
		headCountChange: 2,
	},
	{
		id: "unit-broiler-b",
		farmId: "farm-001",
		name: "Lote engorde B",
		categoryLabel: "Chicken",
		mode: "aggregate",
		status: "active",
		location: "Galpon 2",
		tags: ["broiler", "growth"],
		headCount: 62,
		headCountChange: -1,
	},
	{
		id: "unit-sheep",
		farmId: "farm-001",
		name: "Sheep Unit",
		categoryLabel: "Sheep",
		mode: "individual",
		status: "active",
		location: "North paddock",
		tags: ["breeding"],
	},
	{
		id: "unit-cattle",
		farmId: "farm-001",
		name: "Cattle Unit",
		categoryLabel: "Cattle",
		mode: "individual",
		status: "active",
		location: "South field",
		tags: ["beef"],
	},
	{
		id: "unit-goats",
		farmId: "farm-001",
		name: "Goat Unit",
		categoryLabel: "Goat",
		mode: "individual",
		status: "active",
		location: "East pasture",
		tags: ["dairy"],
	},
	{
		id: "unit-pigs",
		farmId: "farm-001",
		name: "Pig Unit",
		categoryLabel: "Pig",
		mode: "individual",
		status: "active",
		location: "Barn",
		tags: ["meat"],
	},
];

export const v2IndividualSeed: Individual[] = [
	{
		id: "ind-luna",
		unitId: "unit-sheep",
		name: "Luna",
		tag: "SH-001",
		sex: "female",
		status: "active",
		attributes: {
			reproductiveStatus: "pregnant",
			attention: "watch",
			attentionNote: "vence en 6 dias · prenada",
		},
	},
	{
		id: "ind-patch",
		unitId: "unit-sheep",
		name: "Patch",
		tag: "SH-005",
		sex: "male",
		status: "active",
		attributes: {
			attention: "overdue",
			attentionNote: "sin peso en 30 dias",
		},
	},
	{
		id: "ind-dolly",
		unitId: "unit-sheep",
		name: "Dolly",
		tag: "SH-003",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-rex",
		unitId: "unit-sheep",
		name: "Rex",
		tag: "SH-002",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-bessie",
		unitId: "unit-cattle",
		name: "Bessie",
		tag: "CT-002",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-angus",
		unitId: "unit-cattle",
		name: "Angus",
		tag: "CT-001",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-daisy",
		unitId: "unit-cattle",
		name: "Daisy",
		tag: "CT-003",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-bruno",
		unitId: "unit-cattle",
		name: "Bruno",
		tag: "CT-004",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-billy",
		unitId: "unit-goats",
		name: "Billy",
		tag: "GT-001",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-nanny",
		unitId: "unit-goats",
		name: "Nanny",
		tag: "GT-002",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-clover",
		unitId: "unit-goats",
		name: "Clover",
		tag: "GT-003",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-kid",
		unitId: "unit-goats",
		name: "Kid",
		tag: "GT-004",
		sex: "unknown",
		status: "active",
	},
	{
		id: "ind-hammy",
		unitId: "unit-pigs",
		name: "Hammy",
		tag: "PG-001",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-babe",
		unitId: "unit-pigs",
		name: "Babe",
		tag: "PG-002",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-snort",
		unitId: "unit-pigs",
		name: "Snort",
		tag: "PG-003",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-willow",
		unitId: "unit-sheep",
		name: "Willow",
		tag: "SH-006",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-maple",
		unitId: "unit-sheep",
		name: "Maple",
		tag: "SH-007",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-oak",
		unitId: "unit-sheep",
		name: "Oak",
		tag: "SH-008",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-pearl",
		unitId: "unit-sheep",
		name: "Pearl",
		tag: "SH-009",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-frost",
		unitId: "unit-sheep",
		name: "Frost",
		tag: "SH-010",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-mocha",
		unitId: "unit-sheep",
		name: "Mocha",
		tag: "SH-011",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-comet",
		unitId: "unit-cattle",
		name: "Comet",
		tag: "CT-005",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-fern",
		unitId: "unit-cattle",
		name: "Fern",
		tag: "CT-006",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-ruby",
		unitId: "unit-cattle",
		name: "Ruby",
		tag: "CT-007",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-titan",
		unitId: "unit-cattle",
		name: "Titan",
		tag: "CT-008",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-hazel",
		unitId: "unit-cattle",
		name: "Hazel",
		tag: "CT-009",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-onyx",
		unitId: "unit-cattle",
		name: "Onyx",
		tag: "CT-010",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-sprout",
		unitId: "unit-goats",
		name: "Sprout",
		tag: "GT-005",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-thyme",
		unitId: "unit-goats",
		name: "Thyme",
		tag: "GT-006",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-poppy",
		unitId: "unit-goats",
		name: "Poppy",
		tag: "GT-007",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-ridge",
		unitId: "unit-goats",
		name: "Ridge",
		tag: "GT-008",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-bramble",
		unitId: "unit-goats",
		name: "Bramble",
		tag: "GT-009",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-skye",
		unitId: "unit-goats",
		name: "Skye",
		tag: "GT-010",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-truffle",
		unitId: "unit-pigs",
		name: "Truffle",
		tag: "PG-004",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-waffles",
		unitId: "unit-pigs",
		name: "Waffles",
		tag: "PG-005",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-peaches",
		unitId: "unit-pigs",
		name: "Peaches",
		tag: "PG-006",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-grunt",
		unitId: "unit-pigs",
		name: "Grunt",
		tag: "PG-007",
		sex: "male",
		status: "active",
	},
	{
		id: "ind-cocoa",
		unitId: "unit-pigs",
		name: "Cocoa",
		tag: "PG-008",
		sex: "female",
		status: "active",
	},
	{
		id: "ind-bolt",
		unitId: "unit-pigs",
		name: "Bolt",
		tag: "PG-009",
		sex: "male",
		status: "active",
	},
];

export const v2CategorySeed: EventCategory[] = [
	{ id: "cat-eggs", farmId: "farm-001", type: "production", name: "Eggs" },
	{ id: "cat-feed", farmId: "farm-001", type: "expense", name: "Feed" },
	{ id: "cat-egg-sale", farmId: "farm-001", type: "income", name: "Egg sales" },
	{
		id: "cat-health",
		farmId: "farm-001",
		type: "health",
		name: "Health check",
	},
	{
		id: "cat-reproductive",
		farmId: "farm-001",
		type: "reproductive",
		name: "Reproductive",
	},
	{ id: "cat-feed-log", farmId: "farm-001", type: "feed", name: "Feeding" },
];

export const v2InventorySeed: InventoryItem[] = [
	{
		id: "inv-layer",
		farmId: "farm-001",
		name: "Layer Feed",
		stock: 14,
		stockUnit: "kg",
		daysOfCover: 2,
		reorderThreshold: 4,
		status: "critical",
	},
	{
		id: "inv-scratch",
		farmId: "farm-001",
		name: "Scratch Grain",
		stock: 29,
		stockUnit: "kg",
		daysOfCover: 22,
		reorderThreshold: 7,
		status: "ok",
	},
];

export const v2EventSeed: FarmEvent[] = [
	{
		id: "evt-1",
		farmId: "farm-001",
		unitId: "unit-layer-a",
		type: "production",
		categoryId: "cat-eggs",
		occurredAt: toIsoFromToday(0, 7),
		status: "logged",
		quantity: 41,
		notes: "2 rotos",
	},
	{
		id: "evt-2",
		farmId: "farm-001",
		unitId: "unit-layer-a",
		type: "feed",
		categoryId: "cat-feed-log",
		occurredAt: toIsoFromToday(0, 8),
		status: "planned",
		quantity: 7,
		metadata: { priority: "high" },
	},
	{
		id: "evt-3",
		farmId: "farm-001",
		unitId: "unit-sheep",
		individualId: "ind-luna",
		type: "health",
		categoryId: "cat-health",
		occurredAt: toIsoFromToday(0, 15),
		status: "planned",
		metadata: { priority: "high", alert: "urgent" },
		notes: "Seguimiento de preniez",
	},
	{
		id: "evt-egg-d1",
		farmId: "farm-001",
		unitId: "unit-layer-a",
		type: "production",
		categoryId: "cat-eggs",
		occurredAt: toIsoFromToday(-1, 7),
		status: "logged",
		quantity: 45,
	},
	{
		id: "evt-egg-d2",
		farmId: "farm-001",
		unitId: "unit-layer-a",
		type: "production",
		categoryId: "cat-eggs",
		occurredAt: toIsoFromToday(-2, 7),
		status: "logged",
		quantity: 39,
	},
	{
		id: "evt-egg-d3",
		farmId: "farm-001",
		unitId: "unit-layer-a",
		type: "production",
		categoryId: "cat-eggs",
		occurredAt: toIsoFromToday(-3, 7),
		status: "logged",
		quantity: 41,
	},
	{
		id: "evt-egg-d4",
		farmId: "farm-001",
		unitId: "unit-layer-a",
		type: "production",
		categoryId: "cat-eggs",
		occurredAt: toIsoFromToday(-4, 7),
		status: "logged",
		quantity: 35,
	},
	{
		id: "evt-egg-d5",
		farmId: "farm-001",
		unitId: "unit-layer-a",
		type: "production",
		categoryId: "cat-eggs",
		occurredAt: toIsoFromToday(-5, 7),
		status: "logged",
		quantity: 38,
	},
	{
		id: "evt-egg-d6",
		farmId: "farm-001",
		unitId: "unit-layer-a",
		type: "production",
		categoryId: "cat-eggs",
		occurredAt: toIsoFromToday(-6, 7),
		status: "logged",
		quantity: 32,
	},
	{
		id: "evt-4",
		farmId: "farm-001",
		unitId: "unit-layer-a",
		type: "income",
		categoryId: "cat-egg-sale",
		occurredAt: toIsoFromToday(-2, 10),
		status: "logged",
		amount: 210,
	},
	{
		id: "evt-5",
		farmId: "farm-001",
		unitId: "unit-layer-a",
		type: "expense",
		categoryId: "cat-feed",
		occurredAt: toIsoFromToday(-1, 9),
		status: "logged",
		amount: 95,
	},
];
